baseURL = "https://jrdeng.github.io"
languageCode = "zh-CN"
title = "无名的旅人"
theme = "maupassant"
summaryLength = 62
hasCJKLanguage = true

[author]
  name = "jrdeng"

[params]
  author = "jrdeng"
  subtitle = "和其光，同其尘"
  keywords = "Python,github,hugo,blog"
  description = ""

[[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 2

[[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 99

[[params.links]]
    name = "L2M2"
    title = "L2M2"
    url = "https://l2m2.top/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
